### ISSUE TITLE
[typhoon] One Page modular menu not working

### ISSUE THREAD

**Issue by danjames68** [getgrav/grav-premium-issues#131]
I've made a one-page website with Typhoon, based on the one-page skeleton. I can't make the menu work. 

In `modular.md` I've set `onpage_menu = true` -  I haven't touched `navigation` or `macro` templates. I started by making a new theme from Typhoon and if I revert back to Typhoon the menu re-appears but just as a page menu - i.e. showing the 'typography' and 'start here' page links.

I've built a few grav sites before, and this is my second or third with Typhoon - but I'm stumped. I've run `npm update` and `npm ci` to check all the packages are there.

This is the header of modular.md:

```
---
title: 'Property Management in Tuscany'
onpage_menu: true
header_bar:
    background: transparent
    text: light
content:
    items: self@.modular
---
```

Any ideas welcome. I'm stumped.

**Comment by rhukster** [comment]
Hmm.. this does appear to be broken.. I will investigate.

**Comment by rhukster** [comment]
Btw sorry for the late reply, I missed this one in my email.

**Comment by rhukster** [comment]
Turns out this was not ported to Typhoon at all.  The check was there, but no logic to actually make it work.  I've implemented this, but it's really not super useful until I add support for fixed header. This is coming in a future update.

**Comment by rhukster** [comment]
Will be available in next release.

**Comment by PeterB513** [comment]
I just did an update to the new typhoon version. I get all my modular pages on top as a menu item. I have searched where I could switch this off. I also tried to do  `onpage_menu: false` but this didn't solve this. Also did a clear cache.

What I also experienced now is that before userlogin (top right) I get the original menu items. After login I get the menu items / pages I created.   What happened?

**Comment by rhukster** [comment]
I left a bad check in there.  Please edit your `typhoon/templates/modular.html.twig` file, the first line **should** read:

```twig
{% set show_onpage_menu = header.onpage_menu == true %}
```

I'll get a new release out asap

**Comment by rhukster** [comment]
if you have `onpage_menu: true` in a `modular.md` file then it will show the onepage menu in place of the regular menu.  As as you are on another page, it will show the regular menu.  The login and langswitcher (if you are using that) are added via an event and those will be available in both onpage and regular menu.

Please note, that the onpage_menu is really only intended for single-page websites where you don't have other pages.
