### ISSUE TITLE
[seo-magic] Can't generate SEO data anymore (Couldn't connect to server)

### ISSUE THREAD

**Issue by kees-closed** [getgrav/grav-premium-issues#135]
I just upgraded from v2.0.1 to v2.1.1 and now I cannot generate SEO data anymore. In the web UI it says "Invalid AJAX response". And with the CLI it says.
```
bin/plugin seo-magic process

Processing Pages for SEO Data
=============================



In ErrorChunk.php line 64:
                                                                   
  Couldn't connect to server for "http://localhost/sitemap.json".  
                                                                   

In CurlResponse.php line 294:
                                                                   
  Couldn't connect to server for "http://localhost/sitemap.json".  
                                                                   

process [-s|--score] [--] [<url>]
```

I use Redis caching, but I switched to File caching as well, same issue. Sometimes Redis caching is buggy in my experience. Anything else I can try to debug or fix this? My [sitemap](https://www.zeitgeistbeweging.nl/sitemap.json) is readable. But just not by the plugin?

Does the plugin really expect this at localhost? And on port 80?
```
$ curl http://localhost/sitemap.json
curl: (7) Failed connect to localhost:80; Connection refused
$ curl https://localhost/sitemap.json
curl: (7) Failed connect to localhost:443; Connection refused
```

```
bin/gpm version
You are running Grav v1.7.18
```

**Comment by rhukster** [comment]
Sorry I’m traveling at the moment so can’t debug properly until I get back on Monday.  

I think it might be a problem with reaching your site via https.  You would need to ensure you have a valid certificate for that to work.  I can’t test your localhost remotely so that would be something you would to test yourself.  

I did notice that your live site didn’t have a /help page but that should be being skipped if the response is 404 (page not found) but it should also not be in the sitemap either. Is there something weird or different about this page? How come it’s in the sitemap or at least being crawled but doesn’t exist?

**Comment by kees-closed** [comment]
> bin/plugin seo-magic process https://www.zeitgeistbeweging.nl/sitemap.json

That does work indeed, see output below. But the thing is, this used to work fine by default. Especially from the web UI. Now I get this Ajax error, which is probably due to trying to reach the localhost version. That doesn't seem right. Because there is no requirement to have your Grav website reachable via localhost, right? That would make it quite inconvenient as well when you have multiple Grav sites.

```
/bin/plugin seo-magic process https://www.zeitgeistbeweging.nl/sitemap.json

Processing Pages for SEO Data
=============================


200: https://www.zeitgeistbeweging.nl/contact
200: https://www.zeitgeistbeweging.nl/contact/thankyou
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20201216-chapter-report
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20210105-chapter-meeting
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20210202-chapter-meeting
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20210302-chapter-meeting
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20210604-chapter-meeting
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/20210706-chapter-meeting
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/co-initiative-method
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/dse-bijeenkomsten-2021
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/european-meetup-2015
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/getting-our-bearings-on-the-co-initiative
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/ipcc-rapport-reactie
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/nieuwe-website
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/tzm-nl-reboot
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/zday-2010
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/zday-2014
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/zday-2016
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/blog/zday-2017
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/faq
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/over-nl-rbe
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/over-tzm
200: https://www.zeitgeistbeweging.nl/de-zeitgeistbeweging/raak-betrokken
200: https://www.zeitgeistbeweging.nl/events/chapter-meetings
200: https://www.zeitgeistbeweging.nl/events/kalender
200: https://www.zeitgeistbeweging.nl/events/orientatie-meetings
200: https://www.zeitgeistbeweging.nl/events/zday
200: https://www.zeitgeistbeweging.nl/
200: https://www.zeitgeistbeweging.nl/media/boeken
200: https://www.zeitgeistbeweging.nl/media/podcasts
200: https://www.zeitgeistbeweging.nl/media/presentaties
200: https://www.zeitgeistbeweging.nl/media/videos
200: https://www.zeitgeistbeweging.nl/teams/educatie-team
200: https://www.zeitgeistbeweging.nl/teams/fabricage-team
200: https://www.zeitgeistbeweging.nl/teams/it-team
200: https://www.zeitgeistbeweging.nl/teams/it-team/boinc
200: https://www.zeitgeistbeweging.nl/teams/media-team
200: https://www.zeitgeistbeweging.nl/teams/vertaal-team
200: https://www.zeitgeistbeweging.nl/teams/vertaal-team/teksten-poodle-google-docs
200: https://www.zeitgeistbeweging.nl/teams/vertaal-team/videos-dotsub

Completed SEO-Magic processing in 9.3s

                                                                                                                        
 [OK] SEOMagic processed for 41/41 pages                                                                                
```

**Comment by rhukster** [comment]
It should work fine from the Admin interface as that already knows the current URL.  From the CLI, there's now way to know wha the proper URL is to load the sitemap.

**Comment by kees-closed** [comment]
Is there a way I can debug the admin interface? Because I get the "Invalid AJAX response" for some reason. I tailed the logs `backup-default-site-backup.out  backup.log  cache-clear.out  cache-purge.out  email-queue.out  grav.log  popularity  tntsearch-index.out`, but there is no output in there either.

**Comment by rhukster** [comment]
if you are using devtools in chrome, you can examine the XHR request in the "network" tab.  There you can open the response and see the message that is coming back.

**Comment by rhukster** [comment]
Actually my fault!!!! i realized it was broken for all not just you.  I've released v2.1.2 that should be available soon that should fix the issue with the admin regeneration.

**Comment by Aminejohda** [comment]
to be sure is this issue merged? because I'm still getting the same issue
![image](https://user-images.githubusercontent.com/24367628/140110996-b8132915-4492-4846-b1c8-61c959f14924.png)
Thank you

**Comment by rhukster** [comment]
When you go to that URL in your browser does it work? `http://localhost/sitemap.json` 

When you run from the CLI you probably need to tell the script where your site is (as the CLI doesn't know).  like this:

```
bin/plugin seo-magic process http://localhopst/mysite/sitemap.json
```

**Comment by Aminejohda** [comment]
@rhukster yes on browser works correctly, also when I tell the script the right URL still throw the same error

**Comment by rhukster** [comment]
Are you all up to date with Grav + plugins? I can't replicate this, as it just works for me.  Is your site accessible remotely?

**Comment by Aminejohda** [comment]
yes I'm using Grav v1.7.24, Admin v1.10.24, Seo magic v4.0.0, Sitemap v3.0.1
Unfortunately, I'm still testing it locally so it's still not used on production

**Comment by rhukster** [comment]
Yup, those versions look correct. I just tested again and had no issues at all. Are you on windows? Maybe an issue there? Can you try WSL? I'm on mac and can't test windows.

**Comment by Aminejohda** [comment]
sorry. but  I'm also using mac
not sure but I've downgraded in my previous version, and then upgrade only Grav and SEO Magic, but when I've tried to upgrade Seo Magic using the admin dashboard I got this issue, this is the log from Grav
```
 An exception has been thrown during the rendering of a template ("Couldn't connect to server for "http://localhost:8090/sitemap.json"."). - Trace: #0 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #1 /srv/cms/public/cache/twig/f7/f73c5293687ee80a30ec5952001c06eacc23ce2f4417668eecab07a460d88c19.php(116): Twig\Template->display(Array) #2 /srv/cms/public/vendor/twig/twig/src/Template.php(214): __TwigTemplate_2012de747598a8a0352772087e9d7b25d14b6818a95110acb14d42404b09330f->block_field(Array, Array) #3 /srv/cms/public/cache/twig/f7/f73c5293687ee80a30ec5952001c06eacc23ce2f4417668eecab07a460d88c19.php(73): Twig\Template->displayBlock('field', Array, Array) #4 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_2012de747598a8a0352772087e9d7b25d14b6818a95110acb14d42404b09330f->doDisplay(Array, Array) #5 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #6 /srv/cms/public/cache/twig/6e/6e86feb754b20a3acd543dac7f8fd243bdd74dfa24ac21d39046d18b95e71e26.php(240): Twig\Template->display(Array, Array) #7 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_8091cf8af008561dffb271d3320865cc11a3317e2771843202c8ba1b54914d86___1193542000->doDisplay(Array, Array) #8 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #9 /srv/cms/public/cache/twig/6e/6e86feb754b20a3acd543dac7f8fd243bdd74dfa24ac21d39046d18b95e71e26.php(70): Twig\Template->display(Array) #10 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_8091cf8af008561dffb271d3320865cc11a3317e2771843202c8ba1b54914d86->doDisplay(Array, Array) #11 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #12 /srv/cms/public/cache/twig/d3/d3e41b228fdf4f8bf1c4a00ce252df88c8f813b7726ee249e472a7e5c603fc7d.php(112): Twig\Template->display(Array) #13 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_144657039a46792b394ea494212a179ab8d0c604f23767937300477c0b046d26->doDisplay(Array, Array) #14 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #15 /srv/cms/public/cache/twig/5a/5a0703fc688178a8b2b3216cb99c6e9d42cef855dace345e3b1f89d254aeb690.php(264): Twig\Template->display(Array) #16 /srv/cms/public/vendor/twig/twig/src/Template.php(214): __TwigTemplate_6560b084df8f8227288ce5cf6defc42aa99b9be095c8c5a1c8425444aa54137f->block_content(Array, Array) #17 /srv/cms/public/cache/twig/9a/9a4e689240a865fe9f186be9d6412dd7a4fbc33f4b227e635a496657dd2c0850.php(318): Twig\Template->displayBlock('content', Array, Array) #18 /srv/cms/public/vendor/twig/twig/src/Template.php(214): __TwigTemplate_21fc839b5f3e83b9c6a54bab8eb12f19d87c6814795460225c1ae1d7c4b77059->block_content_wrapper(Array, Array) #19 /srv/cms/public/cache/twig/9a/9a4e689240a865fe9f186be9d6412dd7a4fbc33f4b227e635a496657dd2c0850.php(262): Twig\Template->displayBlock('content_wrapper', Array, Array) #20 /srv/cms/public/vendor/twig/twig/src/Template.php(214): __TwigTemplate_21fc839b5f3e83b9c6a54bab8eb12f19d87c6814795460225c1ae1d7c4b77059->block_page(Array, Array) #21 /srv/cms/public/cache/twig/9a/9a4e689240a865fe9f186be9d6412dd7a4fbc33f4b227e635a496657dd2c0850.php(222): Twig\Template->displayBlock('page', Array, Array) #22 /srv/cms/public/vendor/twig/twig/src/Template.php(214): __TwigTemplate_21fc839b5f3e83b9c6a54bab8eb12f19d87c6814795460225c1ae1d7c4b77059->block_body(Array, Array) #23 /srv/cms/public/cache/twig/9a/9a4e689240a865fe9f186be9d6412dd7a4fbc33f4b227e635a496657dd2c0850.php(76): Twig\Template->displayBlock('body', Array, Array) #24 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_21fc839b5f3e83b9c6a54bab8eb12f19d87c6814795460225c1ae1d7c4b77059->doDisplay(Array, Array) #25 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #26 /srv/cms/public/cache/twig/07/075896361fe4c99e795480ee166846bd83ea142952ae3d9b131a735a2cde3b19.php(34): Twig\Template->display(Array, Array) #27 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_764e5b7f92bc7468246209a0710da4b2672ab64ea4404b903985a75a16565bad->doDisplay(Array, Array) #28 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #29 /srv/cms/public/cache/twig/5a/5a0703fc688178a8b2b3216cb99c6e9d42cef855dace345e3b1f89d254aeb690.php(80): Twig\Template->display(Array, Array) #30 /srv/cms/public/vendor/twig/twig/src/Template.php(453): __TwigTemplate_6560b084df8f8227288ce5cf6defc42aa99b9be095c8c5a1c8425444aa54137f->doDisplay(Array, Array) #31 /srv/cms/public/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling(Array, Array) #32 /srv/cms/public/vendor/twig/twig/src/Template.php(432): Twig\Template->display(Array) #33 /srv/cms/public/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array) #34 /srv/cms/public/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array) #35 /srv/cms/public/system/src/Grav/Common/Twig/Twig.php(438): Twig\Environment->render('plugins.html.tw...', Array) #36 /srv/cms/public/system/src/Grav/Common/Service/OutputServiceProvider.php(36): Grav\Common\Twig\Twig->processSite('html') #37 /srv/cms/public/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #38 /srv/cms/public/system/src/Grav/Common/Processors/RenderProcessor.php(40): Pimple\Container->offsetGet('output') #39 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #40 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /srv/cms/public/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #43 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /srv/cms/public/system/src/Grav/Common/Processors/PagesProcessor.php(98): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #46 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /srv/cms/public/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #48 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #49 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #50 /srv/cms/public/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #51 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #52 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #53 /srv/cms/public/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #54 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #55 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #56 /srv/cms/public/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #57 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #58 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /srv/cms/public/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #60 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #61 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #62 /srv/cms/public/user/plugins/admin/classes/plugin/Router.php(65): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #63 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #64 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #65 /srv/cms/public/system/src/Grav/Common/Processors/RequestProcessor.php(63): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #66 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #67 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #68 /srv/cms/public/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #69 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #70 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #71 /srv/cms/public/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #72 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #73 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #74 /srv/cms/public/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #75 /srv/cms/public/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #76 /srv/cms/public/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #77 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #78 /srv/cms/public/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #79 /srv/cms/public/system/src/Grav/Common/Grav.php(303): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #80 /srv/cms/public/index.php(58): Grav\Common\Grav->process() #81 {main} [] []
```

but once I've updated it using CLI the update went fine but again it still not working

**Comment by rhukster** [comment]
Can you paste a copy of your system.yaml? perhaps you have a proxy setup or something?

**Comment by rhukster** [comment]
Also what are you using for a webserver that is using port 8090? Do you have any kind of security that could be blocking the crawler? Like some kind of bot blocking?

**Comment by Aminejohda** [comment]
yaml file under "cms/public/user/config/system.yaml" ?

```YAML
absolute_urls: false
timezone: Europe/Berlin
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: false
force_lowercase_urls: true
custom_base_url: null
username_regex: '^[a-z0-9_-]{3,16}$'
pwd_regex: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}'
intl_enabled: true
http_x_forwarded:
  protocol: true
  host: false
  port: true
  ip: true
languages:
  supported:
    - de
    - en
    - es
  default_lang: de
  include_default_lang: true
  include_default_lang_file_extension: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
  pages_fallback_only: false
home:
  alias: /home
  hide_in_urls: false
pages:
  type: regular
  theme: lingoking
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: null
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  never_cache_twig: false
  events:
    page: true
    twig: true
  markdown:
    extra: false
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
    valid_link_attributes:
      - rel
      - target
      - id
      - class
      - classes
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  append_url_extension: null
  expires: 604800
  cache_control: no-cache
  last_modified: false
  etag: true
  vary_accept_encoding: false
  redirect_default_code: '301'
  redirect_trailing_slash: 1
  redirect_default_route: 0
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  hide_empty_folders: false
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  purge_at: '0 4 * * *'
  clear_at: '0 3 * * *'
  clear_job_type: standard
  clear_images_by_default: true
  cli_compatibility: false
  lifetime: 604800
  gzip: true
  allow_webserver_gzip: false
  redis:
    socket: '0'
    password: null
    database: null
    server: null
    port: null
  memcache:
    server: null
    port: null
  memcached:
    server: null
    port: null
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  safe_functions: {  }
  safe_filters: {  }
  umask_fix: false
assets:
  css_pipeline: true
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: true
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: false
  js_minify: false
  enable_asset_timestamp: true
  enable_asset_sri: false
  collections:
    jquery: 'system://assets/jquery/jquery-3.x.min.js'
errors:
  display: 0
  log: true
log:
  handler: file
  syslog:
    facility: local6
debugger:
  enabled: false
  provider: clockwork
  censored: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: false
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: false
  seofriendly: true
  cls:
    auto_sizes: true
    aspect_ratio: false
    retina_scale: '1'
  defaults:
    loading: auto
media:
  enable_media_timestamp: false
  unsupported_inline_types: null
  allowed_fallback_types: null
  auto_metadata_exif: false
  upload_limit: 33554432
session:
  enabled: true
  initialize: true
  timeout: 1800
  name: lingoking-site
  uniqueness: path
  secure: false
  httponly: true
  samesite: Lax
  split: true
  domain: null
  path: null
gpm:
  releases: stable
  proxy_url: null
  method: auto
  verify_peer: true
  official_gpm_only: true
accounts:
  type: regular
  storage: file
flex:
  cache:
    index:
      enabled: true
      lifetime: 60
    object:
      enabled: true
      lifetime: 600
    render:
      enabled: true
      lifetime: 600
strict_mode:
  yaml_compat: true
  twig_compat: true
  blueprint_compat: false
gtm:
  id: ''
  slug: ''
  iframe: ''
```

**Comment by Aminejohda** [comment]
I'm using docker within nginx webserver

**Comment by rhukster** [comment]
Well i'm sure its something related to the Docker container.  The machine/port is probably different inside the container than outside. Running a browser is accessing the container from outside, but when you are running CLI commands, you are logged into the container.  This is a VM so it's a like having two machines.  They are not going to be the same ip/ports for each.

**Comment by Aminejohda** [comment]
yes,  indeed I need to put the service name instead of localhost, thank you so much for your help :)

**Comment by Aminejohda** [comment]
@rhukster Sorry maybe it's not the correct issue to ask this question, but how can I let SEO-Magic crawler works for the whole website that is protected with a .htaccess username and password (I'm trying to test it on the staging server)
Thank you

**Comment by rhukster** [comment]
This is more of a server question but my advice is to add an entry in you htaccess that allows the crawler’s specific user agent. The agent string is configurable in the settings. You can Google how to do this. 

Alternatively maybe allow the up of the server itself?
