### ISSUE TITLE
[seo-magic] Webshot unauthorized

### ISSUE THREAD

**Issue by dumiller** [getgrav/grav-premium-issues#358]
We are seeing an image of "Unauthorized Webshot is an SEO Magic plugin feature" across socials. We have registered and unregistered several combinations of our website URL but nothing works. We have cleared all cache and regenerated SEO Magic data. I am not really sure where to start with troubleshooting this issue. Any help would be appreciated. 

[](https://www.opengraph.xyz/url/https%3A%2F%2Fwww.guardvue.net
)
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/19696594/227400934-3b0e7e18-48c5-4fd1-8438-ee035b3dfda3.png">

**Comment by dumiller** [comment]
Looking for a response and help with out issue. Thanks.

**Comment by w00fz** [comment]
Hey @dumiller,

Can you try unregistering and registering again, while keeping an eye on the Network tab of the Browser Inspector? I do not see any activity for that domain on the webshot server which is unusual.

**Comment by w00fz** [comment]
Hey @dumiller,

Sorry it took this long but I was baffled. Apparently there was a system issue running on our getgrav server that was preventing the registered sites to synchronize with webshot. This seems to have been the case for quite a while and your issue helped me figure it out.

It should now be fixed and you should be seeing webshot working for your site!

Thank you for the assist on this.

**Comment by dumiller** [comment]
We are still getting an unauthorized webshot image. We clreared the cache and manually deleted the image in /var/www/html/grav/cache/seo-magic/images Once the image we re generated it came back as before "Unauthorized"

**Comment by w00fz** [comment]
That is odd because I can definitely see the images generated for sub pages (for example this one blog post:  https://www.guardvue.net/blog/nvrs-vs-cloud-based-vsaas-exploring-their-pros-and-cons/seomagic-image).

Can you try clearing all cache, including that seo-magic folder? When I hit the webshot server directly with your URL I do not get unauthorized any longer. I think somewhere it's still holding onto that old generated image.
